{% set name = "envs-manager" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envs_manager-{{ version }}.tar.gz
  sha256: 55677df9e73b6e3730e00f3e231b52eb3917bfed6f6b65682de86a0060fb0357

build:
  noarch: python
  entry_points:
    - envs-manager = envs_manager.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - pyyaml
    - requests

test:
  imports:
    - envs_manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/envs-manager/
  summary: A manager for Python environments and packages managers
  dev_url: https://github.com/spyder-ide/envs-manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalthviz
