{% set name = "envs-manager" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/envs_manager-{{ version }}.tar.gz
  sha256: 9ed78d1837ed0e98d45fa96c54c9794036fe8a48e03a9a6c38c55d01692447cf

build:
  noarch: python
  entry_points:
    - envs-manager = envs_manager.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - pyyaml
    - requests

test:
  imports:
    - envs_manager
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/envs-manager/
  summary: A manager for Python environments and packages managers
  dev_url: https://github.com/spyder-ide/envs-manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dalthviz
